# Generated by Django 6.0.7 on 2026-07-31 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_garmin_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'start_datetime'], name='workout_user_time'),
        ),
    ]
