# Generated by Django 4.2.30 on 2026-07-25 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0002_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillInstructorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('matrix_homeserver', models.CharField(max_length=200)),
                ('matrix_access_token', models.CharField(max_length=512)),
                ('matrix_room_id', models.CharField(max_length=120)),
                ('matrix_bot_display_name', models.CharField(blank=True, default='', max_length=60)),
                ('comment_on_activity', models.BooleanField(default=True)),
                ('send_push_on_activity', models.BooleanField(default=False, help_text='Also send a browser push notification to every subscribed participant.')),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('messages_posted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drill_instructor', to='competition.competition')),
            ],
            options={
                'ordering': ['competition__name'],
            },
        ),
        migrations.CreateModel(
            name='DrillInstructorPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('system_prompt', models.TextField()),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrillInstructorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_event_id', models.CharField(blank=True, default='', max_length=120)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='drill_instructor.drillinstructorconfig')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drill_instructor_messages', to='workouts.workout')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddField(
            model_name='drillinstructorconfig',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='drill_instructor.drillinstructorpersona'),
        ),
    ]
