# Generated by Django 6.0.7 on 2026-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0004_persona_identity'),
        ('workouts', '0003_workout_workout_user_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drillinstructormessage',
            index=models.Index(fields=['config', '-posted_at'], name='drill_msg_config_time'),
        ),
    ]
