# Generated by Django 5.2.16 on 2026-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0005_drillinstructormessage_drill_msg_config_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillinstructorconfig',
            name='nudge_on_inactivity',
            field=models.BooleanField(default=True, help_text='If a whole day passes without any workout in a running competition, the instructor posts one motivational nudge to keep the group active.'),
        ),
        migrations.AddField(
            model_name='drillinstructormessage',
            name='kind',
            field=models.CharField(choices=[('activity', 'Workout comment'), ('test', 'Test message'), ('nudge', 'Inactivity nudge')], default='activity', help_text='What triggered this message (a workout, a test, or a quiet-day nudge).', max_length=12),
        ),
    ]
