# Generated by Django 5.2.16 on 2026-08-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0010_persona_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drillinstructormessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='drill_instructor.drillinstructormessage'),
        ),
        migrations.AddField(
            model_name='drillinstructormessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drill_instructor_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drillinstructormessage',
            name='kind',
            field=models.CharField(choices=[('activity', 'Workout comment'), ('test', 'Test message'), ('nudge', 'Inactivity nudge'), ('push', 'Random group push'), ('reply', 'Participant reply'), ('reaction', 'Coach reaction')], default='activity', help_text="What triggered this message (a workout, a test, a quiet-day nudge, a random group push, a participant reply, or the coach's reaction to one).", max_length=12),
        ),
    ]
