# Generated by Django 5.2.17 on 2026-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0027_persona_midi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillinstructormessage',
            name='kind',
            field=models.CharField(choices=[('activity', 'Workout comment'), ('test', 'Test message'), ('nudge', 'Inactivity nudge'), ('push', 'Random group push'), ('reply', 'Participant reply'), ('reaction', 'Coach reaction'), ('photo', 'Participant photo post'), ('order', 'Daily order'), ('sigh', 'Order failure'), ('dunce', 'Dunce crowning'), ('handover', 'Weekly coach handover'), ('echo', 'Legend Echo minted'), ('claim', 'Legend Echo claimed'), ('war', 'Legend Echo war')], default='activity', help_text="What triggered this message (a workout, a test, a quiet-day nudge, a random group push, a participant reply, or the coach's reaction to one).", max_length=12),
        ),
        migrations.AlterField(
            model_name='drillinstructorpersona',
            name='midi',
            field=models.FileField(blank=True, help_text='Optional looping MIDI bed for this coach. Served only through the authenticated persona MIDI endpoint, never public /media/.', null=True, upload_to='coach_midi/'),
        ),
    ]
