# Generated by Django 5.2.17 on 2026-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0031_daily_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillinstructorpersona',
            name='midi',
        ),
        migrations.AlterField(
            model_name='drillinstructorconfig',
            name='daily_prompt',
            field=models.CharField(blank=True, default='', help_text="Standing instruction for the coach's daily morning post, passed to the AI exactly as written (1:1). The coach answers in persona style.", max_length=500),
        ),
    ]
