# Generated by Django 5.2.17 on 2026-09-29 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0032_remove_drillinstructorpersona_midi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComebackPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompts_enabled', models.BooleanField(default=True)),
                ('dismissed_until', models.DateField(blank=True, null=True)),
                ('support_opt_in', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comeback_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
