# Generated by Django 5.2.17 on 2026-09-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0035_retire_generic_coach_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendecho',
            name='photo_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drillinstructormessage',
            name='kind',
            field=models.CharField(choices=[('activity', 'Workout comment'), ('test', 'Test message'), ('nudge', 'Inactivity nudge'), ('push', 'Random group push'), ('reply', 'Participant reply'), ('reaction', 'Coach reaction'), ('photo', 'Participant photo post'), ('order', 'Daily order'), ('sigh', 'Order failure'), ('dunce', 'Dunce crowning'), ('handover', 'Weekly coach handover'), ('echo', 'Legend Echo minted'), ('claim', 'Legend Echo claimed'), ('war', 'Legend Echo war'), ('briefing', 'Daily owner briefing'), ('gap', 'Material standings gap change')], default='activity', help_text="Identifies the event for filtering historical coach and challenge messages; legacy message kinds remain for compatibility.", max_length=12),
        ),
    ]
