# Generated by Django 5.2.17 on 2026-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_instructor', '0036_legendecho_photo_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillinstructorpersona',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese'), ('it', 'Italian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('tr', 'Turkish'), ('ru', 'Russian'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], default='en', help_text="Language this coach replies in. Does not change the persona's voice.", max_length=8),
        ),
    ]
