"""VAPID keypair handling for Web Push.

Resolution order:
  1. ``VAPID_PUBLIC_KEY`` and ``VAPID_PRIVATE_KEY`` env vars (preferred
     for production - generate once with ``openssl`` or ``py_vapid``).
  2. A persisted keypair in ``DATA_DIR/vapid.json`` (auto-generated on
     first startup and reused across restarts). The private key is
     Fernet-encrypted at rest (same helpers as Site Settings / OAuth
     tokens); plaintext legacy files are upgraded on the next write.
  3. A freshly-generated keypair (development only).

The public key is safe to expose; the private key stays on the server.
"""

import base64
import json
import logging
import os
from pathlib import Path

from django.conf import settings

logger = logging.getLogger(__name__)

_VAPID_CACHE: dict | None = None
_DEFAULT_SUBJECT = "mailto:admin@example.com"


def _encrypt_vapid_private(value: str) -> str:
    """Fernet-encrypt a VAPID private key for disk; leave ciphertext alone."""
    if not value or value.startswith("gAAAA"):
        return value
    from custom_user.token_crypto import encrypt_token
    return encrypt_token(value)


def _decrypt_vapid_private(value: str) -> str:
    """Decrypt a stored VAPID private key (plaintext-compatible)."""
    if not value:
        return value
    from custom_user.token_crypto import decrypt_token
    return decrypt_token(value)


def _write_vapid_file(path: Path, payload: dict) -> None:
    """Persist vapid.json with the private key encrypted and mode 0o600."""
    to_store = dict(payload)
    priv = to_store.get("private") or ""
    to_store["private"] = _encrypt_vapid_private(priv)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        json.dump(to_store, f)
    os.chmod(path, 0o600)


def _public_to_b64url(value: str) -> str:
    """Normalise a VAPID public key to the raw base64url form browsers need.

    ``PushManager.subscribe()`` expects the 65-byte uncompressed EC point,
    base64url-encoded without padding or PEM armour. Keys generated by this
    module (or pinned via env) may instead be PEM strings - which breaks
    the browser's ``atob()`` ("string to be decoded is not correctly
    encoded"). Convert those on the fly; anything already in base64url
    form is passed through unchanged.
    """
    value = (value or "").strip()
    if not value or not value.startswith("-----BEGIN"):
        return value
    try:
        from cryptography.hazmat.primitives import serialization

        pub = serialization.load_pem_public_key(value.encode("utf-8"))
        raw = pub.public_bytes(
            serialization.Encoding.X962,
            serialization.PublicFormat.UncompressedPoint,
        )
        return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")
    except Exception as exc:  # noqa: BLE001 - a broken key must not take the app down
        logger.warning("Could not convert PEM VAPID public key to base64url: %s", exc)
        return value


def _ensure_str(value) -> str:
    """Some ``py_vapid`` versions return ``bytes`` from ``*_pem()``."""
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return value


def _vapid_path() -> Path:
    data_dir = getattr(settings, "DATA_DIR", Path(settings.BASE_DIR) / "data")
    return Path(data_dir) / "vapid.json"


def ensure_vapid_keys():
    """Load or generate the VAPID keypair and expose them on Django settings."""
    global _VAPID_CACHE

    pub = os.environ.get("VAPID_PUBLIC_KEY", "").strip()
    priv = os.environ.get("VAPID_PRIVATE_KEY", "").strip()
    subject = os.environ.get("VAPID_SUBJECT", _DEFAULT_SUBJECT).strip()

    if pub and priv:
        _VAPID_CACHE = {"public": _public_to_b64url(pub), "private": priv, "subject": subject}
    else:
        path = _vapid_path()
        if path.is_file():
            try:
                with path.open() as f:
                    _VAPID_CACHE = json.load(f)
                # Heal keypairs persisted by older versions that stored the
                # public key in PEM form (broke browser subscription).
                stored_public = (_VAPID_CACHE or {}).get("public", "")
                normalised_public = _public_to_b64url(stored_public)
                public_changed = bool(normalised_public and normalised_public != stored_public)
                if public_changed:
                    _VAPID_CACHE["public"] = normalised_public
                # Decrypt private for runtime; rewrite file when the on-disk
                # private was still plaintext (or public needed healing).
                stored_private = (_VAPID_CACHE or {}).get("private", "") or ""
                plaintext_private = _decrypt_vapid_private(stored_private)
                _VAPID_CACHE["private"] = plaintext_private
                needs_rewrite = public_changed or (
                    bool(stored_private) and not stored_private.startswith("gAAAA")
                )
                if needs_rewrite:
                    try:
                        _write_vapid_file(path, _VAPID_CACHE)
                        logger.info("Normalised / re-encrypted persisted VAPID keypair at %s", path)
                    except Exception as exc:  # noqa: BLE001
                        logger.warning("Could not rewrite %s: %s", path, exc)
            except Exception as exc:
                logger.warning("Failed to read persisted VAPID keys: %s", exc)
                _VAPID_CACHE = None

        if not _VAPID_CACHE or not _VAPID_CACHE.get("public"):
            try:
                from py_vapid import Vapid  # type: ignore
                vapid = Vapid()
                vapid.generate_keys()
                _VAPID_CACHE = {
                    "public": _public_to_b64url(_ensure_str(vapid.public_pem())),
                    "private": _ensure_str(vapid.private_pem()),
                    "subject": subject,
                }
                # Persist with Fernet-encrypted private key and mode 0o600.
                _write_vapid_file(path, _VAPID_CACHE)
                logger.info("Generated and persisted new VAPID keypair at %s", path)
            except ImportError:
                logger.error("py_vapid is not installed; push notifications will not work.")
                _VAPID_CACHE = {"public": "", "private": "", "subject": subject}

    settings.VAPID_PUBLIC_KEY = _VAPID_CACHE.get("public", "")
    settings.VAPID_PRIVATE_KEY = _VAPID_CACHE.get("private", "")
    settings.VAPID_SUBJECT = _VAPID_CACHE.get("subject", subject)


def get_vapid_public_key() -> str:
    """Public key for the browser to subscribe with."""
    if _VAPID_CACHE is None:
        ensure_vapid_keys()
    return _VAPID_CACHE.get("public", "") if _VAPID_CACHE else ""


def get_vapid_private_key() -> str:
    """Server-side private key - never expose via the API."""
    if _VAPID_CACHE is None:
        ensure_vapid_keys()
    return _VAPID_CACHE.get("private", "") if _VAPID_CACHE else ""


_VAPID_INSTANCE_CACHE = {"key": None, "instance": None}


def get_vapid_instance():
    """Return a ready-to-sign ``py_vapid.Vapid`` for webpush().

    The stored/env private key may be PEM text (auto-generated pairs
    are persisted that way) or base64url DER. pywebpush hands any
    non-file string to ``Vapid.from_string()``, which only understands
    base64url DER - so a PEM string made EVERY send die with "Could not
    deserialize key data". Normalise the format here instead.

    Memoized per key value: EC key parsing on every subscription send
    (fan-outs loop over participants x devices) is wasted work.
    """
    from py_vapid import Vapid
    key = get_vapid_private_key()
    if not key:
        return None
    if _VAPID_INSTANCE_CACHE["key"] != key:
        instance = Vapid.from_pem(key.encode()) if "-----BEGIN" in key else Vapid.from_string(private_key=key)
        _VAPID_INSTANCE_CACHE.update({"key": key, "instance": instance})
    return _VAPID_INSTANCE_CACHE["instance"]


def get_vapid_subject() -> str:
    if _VAPID_CACHE is None:
        ensure_vapid_keys()
    return _VAPID_CACHE.get("subject", _DEFAULT_SUBJECT) if _VAPID_CACHE else _DEFAULT_SUBJECT
