# Generated by Django 6.0.7 on 2026-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='garmin_id',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
