"""Deterministic Expedition scheduling and normalized score movement.

Route geometry and milestone identity are code-defined, never generated by
runtime AI. Score contributions are recomputed from capped challenge scores
and stored as unique participant/week rollups, so retries and rescoring do
not increment the group's progress twice.
"""

import datetime
from datetime import date, timedelta
from decimal import Decimal, ROUND_HALF_UP

from django.apps import apps
from django.db import transaction
from django.db.models import Q, Sum
from django.utils import timezone

from .expedition_variants import (
    BASECAMP_HOLD_RATIO,
    OBJECTIVE_BASECAMP,
    OBJECTIVE_RESCUE,
    SHORTCUT_RIDGE,
    STORM_GRACE_PERCENT,
    TWIST_ROPE,
    TWIST_SHORTCUT,
    build_twist_plan,
    cap_multiplier,
    decide_shortcut,
    shortcut_adjustment,
    twist_for_week,
)


ROUTE_TEMPLATE_ID = "trail-v1"
WEEKLY_PERSONAL_CAP = Decimal("100.00")
ZERO = Decimal("0.00")
PERCENT_QUANTUM = Decimal("0.1")

# (stage key, milestone key, route position fraction, progress threshold)
ROUTE_MILESTONES = (
    ("departure", "trailhead", 0, 1, Decimal("0.00")),
    ("crossing", "river-crossing", 1, 3, Decimal("0.25")),
    ("ascent", "high-pass", 2, 3, Decimal("0.60")),
    ("arrival", "finale", 1, 1, Decimal("1.00")),
)

ROUTE_ASSET_KEYS = {
    "trailhead": "trailhead-v1",
    "river-crossing": "river-crossing-v1",
    "high-pass": "high-pass-v1",
    "finale": "finale-v1",
}
APPROVED_PERSONA_ASSET_KEYS = frozenset({
    "butler", "captain", "cheerleader", "megaphone", "ninja",
    "robot", "roast", "rocket", "sergeant", "zen",
})

DEFAULT_COACH = {
    "id": None,
    "key": "trail-guide",
    "name": "Trail Guide",
    "avatar": "🧭",
    "avatar_asset_key": None,
    "theme_color": "#426b55",
    "source": "default",
}


def _round_fraction_half_up(value, numerator, denominator):
    """Round a non-negative rational to the nearest integer, ties upward."""
    return (2 * value * numerator + denominator) // (2 * denominator)


def build_milestone_schedule(start_date: date, end_date: date, shortcut=None) -> list[dict]:
    """Return stable milestone IDs and proportional date windows.

    The route uses the challenge's inclusive dates: the trailhead is fixed to
    ``start_date`` and the finale to ``end_date``. Short challenges may place
    multiple landmarks on the same day while keeping their stable IDs/order.
    ``shortcut`` is ``(milestone_id, extra_fraction, days_earlier)`` when the
    crew voted for the ridge: that one landmark opens earlier and needs more
    route; everything else stays planned.
    """
    if not isinstance(start_date, date) or not isinstance(end_date, date):
        raise ValueError("Expedition dates must be date values.")
    if end_date < start_date:
        raise ValueError("Expedition end date must not precede its start date.")

    span_days = (end_date - start_date).days
    schedule = []
    previous_target = start_date
    for sequence, (stage_id, milestone_id, numerator, denominator, progress_fraction) in enumerate(ROUTE_MILESTONES):
        offset = _round_fraction_half_up(span_days, numerator, denominator)
        target_on = start_date + timedelta(days=offset)
        opens_on = previous_target
        if shortcut and shortcut[0] == milestone_id and milestone_id != "finale":
            progress_fraction = min(Decimal("0.99"), progress_fraction + shortcut[1])
            opens_on = max(start_date, previous_target - shortcut[2])
        schedule.append({
            "stage_id": stage_id,
            "milestone_id": milestone_id,
            "sequence": sequence,
            "opens_on": opens_on,
            "target_on": target_on,
            "progress_fraction": progress_fraction,
        })
        previous_target = target_on
    return schedule


def current_expedition_coach(competition):
    """Resolve the active competition persona, with a documented default."""
    from drill_instructor.models import DrillInstructorConfig

    config = (
        DrillInstructorConfig.objects.select_related("persona")
        .filter(competition=competition, enabled=True)
        .first()
    )
    if config is None:
        return DEFAULT_COACH.copy()

    persona = config.persona
    return {
        "id": persona.pk,
        "key": f"persona-{persona.pk}",
        "name": persona.name,
        "avatar": persona.avatar,
        "avatar_asset_key": (
            persona.avatar if persona.avatar in APPROVED_PERSONA_ASSET_KEYS else None
        ),
        "theme_color": persona.theme_color,
        "source": "competition",
    }


def synchronize_expedition(campaign, today=None, now=None):
    """Reconcile a campaign before launch; lock dates and membership at start."""
    from .models import ExpeditionCampaign, ExpeditionMilestone

    if not campaign.pk:
        raise ValueError("Save the Expedition campaign before synchronizing it.")

    today = today or timezone.localdate()
    now = now or timezone.now()

    # Most reads need no mutation: avoid serializing every participant's API
    # request on a row lock, and avoid rewriting the same pre-launch schedule.
    current = ExpeditionCampaign.objects.select_related("competition").get(
        pk=campaign.pk
    )
    before_start = current.locked_at is None and today < current.start_date
    dates_changed = before_start and (
        current.start_date,
        current.end_date,
    ) != (current.competition.start_date, current.competition.end_date)
    needs_lock = current.locked_at is None and today >= current.start_date
    shortcut = shortcut_adjustment(current.twist_state)
    planned = build_milestone_schedule(
        current.competition.start_date if dates_changed else current.start_date,
        current.competition.end_date if dates_changed else current.end_date,
        shortcut=shortcut,
    )
    expected_milestones = [
        (
            item["milestone_id"], item["stage_id"], item["sequence"],
            item["opens_on"], item["target_on"], item["progress_fraction"],
            ROUTE_ASSET_KEYS.get(item["milestone_id"], ""),
        )
        for item in planned
    ]
    actual_milestones = list(
        current.milestones.order_by("sequence").values_list(
            "milestone_id", "stage_id", "sequence", "opens_on", "target_on",
            "progress_fraction", "approved_asset_key",
        )
    )
    milestones_stale = actual_milestones != expected_milestones
    if not (dates_changed or needs_lock or milestones_stale):
        return current

    with transaction.atomic():
        current = ExpeditionCampaign.objects.select_for_update().select_related(
            "competition"
        ).get(pk=campaign.pk)
        schedule_changed = False

        if current.locked_at is None and today < current.start_date:
            competition = current.competition
            if (current.start_date, current.end_date) != (
                competition.start_date,
                competition.end_date,
            ):
                current.start_date = competition.start_date
                current.end_date = competition.end_date
                schedule_changed = True

        planned = build_milestone_schedule(
            current.start_date, current.end_date, shortcut=shortcut_adjustment(current.twist_state),
        )
        if current.locked_at is None and today >= current.start_date:
            current.locked_at = now
            participant_ids = set(current.competition.user.values_list("pk", flat=True))
            participant_ids.add(current.competition.owner_id)
            current.participant_ids_snapshot = sorted(participant_ids)
            # The season's twists are dealt once, at launch, from the locked
            # calendar and crew size - never re-rolled on later reads.
            current.twist_plan = build_twist_plan(
                list(_score_periods(current.start_date, current.end_date)),
                len(participant_ids),
                seed=current.pk,
            )
            schedule_changed = True

        if schedule_changed:
            current.save()

        has_milestones = current.milestones.exists()
        if schedule_changed or milestones_stale or not has_milestones:
            milestone_ids = []
            for item in planned:
                milestone_ids.append(item["milestone_id"])
                ExpeditionMilestone.objects.update_or_create(
                    campaign=current,
                    milestone_id=item["milestone_id"],
                    defaults={
                        "stage_id": item["stage_id"],
                        "sequence": item["sequence"],
                        "opens_on": item["opens_on"],
                        "target_on": item["target_on"],
                        "progress_fraction": item["progress_fraction"],
                        "approved_asset_key": ROUTE_ASSET_KEYS.get(
                            item["milestone_id"], ""
                        ),
                    },
                )
            if current.locked_at is None:
                current.milestones.exclude(milestone_id__in=milestone_ids).delete()

        return current


def _score_periods(start_date, end_date):
    """Yield challenge-clipped ISO-week windows in Django's active timezone."""
    cursor = start_date
    end_exclusive = end_date + timedelta(days=1)
    active_tz = timezone.get_current_timezone()
    while cursor < end_exclusive:
        monday = cursor - timedelta(days=cursor.weekday())
        next_monday = monday + timedelta(days=7)
        period_end = min(next_monday, end_exclusive)
        covered_days = (period_end - cursor).days
        cap = (
            WEEKLY_PERSONAL_CAP * Decimal(covered_days) / Decimal(7)
        ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        start_dt = timezone.make_aware(
            datetime.datetime.combine(cursor, datetime.time.min), active_tz,
        )
        end_dt = timezone.make_aware(
            datetime.datetime.combine(period_end, datetime.time.min), active_tz,
        )
        yield monday, cursor, period_end, start_dt, end_dt, cap
        cursor = period_end


def _current_participant_ids(competition):
    participant_ids = set(competition.user.values_list("pk", flat=True))
    participant_ids.add(competition.owner_id)
    return participant_ids


def _progress_percent(earned, target):
    if target <= ZERO:
        return Decimal("0.0")
    return min(
        Decimal("100.0"),
        (earned / target * Decimal("100")).quantize(
            PERCENT_QUANTUM,
            rounding=ROUND_HALF_UP,
        ),
    )


def _effective_cap(campaign, week_start, cap):
    """The week's personal ceiling after the twist (storm x1.5, rest x0.5).

    The route *target* always uses the base cap, so a storm week is extra
    ground to gain and a rest week is ground the crew accepts to give up.
    """
    multiplier = cap_multiplier(twist_for_week(campaign.twist_plan, week_start))
    return (cap * multiplier).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _weekly_crew_totals(campaign, week_starts):
    """{week_start: crew points} from the materialized rollups."""
    from .models import ExpeditionContribution

    rows = (
        ExpeditionContribution.objects.filter(campaign=campaign, week_start__in=week_starts)
        .values("week_start").annotate(total=Sum("normalized_points"))
    )
    return {row["week_start"]: Decimal(str(row["total"] or 0)) for row in rows}


def basecamp_status(campaign, periods, participant_count, today, week_totals):
    """Tents standing: +1 per held week, -1 per missed week, never below 0.

    A week is held when the crew filled ``BASECAMP_HOLD_RATIO`` of its
    (twist-adjusted) ceiling. The running week counts as held as soon as it
    crosses the line and is never counted as missed before it ends.
    """
    held = 0
    missed = 0
    tents = 0
    this_week = None
    for week_start, period_start, period_end, _s, _e, cap in periods:
        if period_start > today:
            break
        ceiling = _effective_cap(campaign, week_start, cap) * participant_count
        needed = (ceiling * BASECAMP_HOLD_RATIO).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        earned = week_totals.get(week_start, ZERO)
        is_held = ceiling > ZERO and earned >= needed
        running = period_start <= today < period_end
        if is_held:
            held += 1
            tents += 1
        elif not running:
            missed += 1
            tents = max(0, tents - 1)
        if running:
            this_week = {
                "held": is_held,
                "earned_points": float(earned),
                "needed_points": float(needed),
            }
    weeks_total = len(periods)
    return {
        "tents": tents,
        "held_weeks": held,
        "missed_weeks": missed,
        "weeks_total": weeks_total,
        "this_week": this_week,
        "progress_percent": _progress_percent(Decimal(tents), Decimal(weeks_total)) if weeks_total else Decimal("0.0"),
    }


def objective_progress_percent(campaign, base_percent, periods, participant_count, today):
    """The percentage that drives landmarks: route share, or tents for base camp."""
    if campaign.objective != OBJECTIVE_BASECAMP:
        return base_percent
    week_totals = _weekly_crew_totals(campaign, [period[0] for period in periods])
    return basecamp_status(campaign, periods, participant_count, today, week_totals)["progress_percent"]


def _rope_week_points(competition, participant_ids, start_dt, end_dt):
    """Per-participant points for a rope week: a day counts only when at
    least two crew members scored on that local day."""
    from .models import Points

    rows = (
        Points.objects.filter(
            Q(goal__competition_id=competition.pk) | Q(award__competition_id=competition.pk),
            workout__user_id__in=participant_ids,
            workout__start_datetime__gte=start_dt,
            workout__start_datetime__lt=end_dt,
        ).distinct()
        .values("workout__user_id", "workout__start_datetime")
        .annotate(total=Sum("points_capped"))
    )
    by_day = {}
    for row in rows:
        day = timezone.localtime(row["workout__start_datetime"]).date()
        by_day.setdefault(day, {}).setdefault(row["workout__user_id"], ZERO)
        by_day[day][row["workout__user_id"]] += Decimal(str(row["total"] or 0))
    totals = {}
    for day, per_user in by_day.items():
        if len([uid for uid, pts in per_user.items() if pts > ZERO]) < 2:
            continue
        for uid, pts in per_user.items():
            totals[uid] = totals.get(uid, ZERO) + pts
    return totals


def active_twist(campaign, periods, today):
    """The twist of the running week, with its window, or None."""
    for week_start, period_start, period_end, _s, _e, _cap in periods:
        if period_start <= today < period_end:
            kind = twist_for_week(campaign.twist_plan, week_start)
            if kind:
                return {
                    "kind": kind,
                    "week_start": period_start,
                    "week_end": period_end - timedelta(days=1),
                }
            return None
    return None


def settle_shortcut(campaign, periods, participant_ids, today, force=False):
    """Turn shortcut votes into a route decision once the vote week is over
    (or every crew member has voted). Idempotent; returns the state."""
    from .models import ExpeditionCampaign

    state = dict(campaign.twist_state or {})
    shortcut = dict(state.get("shortcut") or {})
    if shortcut.get("result"):
        return state
    vote_week = next(
        (period for period in periods if twist_for_week(campaign.twist_plan, period[0]) == TWIST_SHORTCUT),
        None,
    )
    if vote_week is None:
        return state
    week_end = vote_week[2]  # exclusive
    votes = {str(k): v for k, v in (shortcut.get("votes") or {}).items()}
    everyone_voted = participant_ids and all(str(pk) in votes for pk in participant_ids)
    if not (force or today >= week_end or everyone_voted):
        return state
    result = decide_shortcut(votes, len(participant_ids))
    target = None
    if result == SHORTCUT_RIDGE:
        target = next(
            (m.milestone_id for m in campaign.milestones.order_by("sequence")
             if not m.completed_at and m.milestone_id != "finale"),
            None,
        )
    shortcut.update({
        "votes": votes,
        "result": result,
        "milestone_id": target,
        "decided_on": today.isoformat(),
    })
    state["shortcut"] = shortcut
    ExpeditionCampaign.objects.filter(pk=campaign.pk).update(twist_state=state)
    campaign.twist_state = state
    # Apply the ridge to the route right away instead of waiting for the
    # next synchronization pass.
    adjustment = shortcut_adjustment(state)
    if adjustment:
        for item in build_milestone_schedule(campaign.start_date, campaign.end_date, shortcut=adjustment):
            if item["milestone_id"] == adjustment[0]:
                campaign.milestones.filter(milestone_id=item["milestone_id"]).update(
                    opens_on=item["opens_on"], progress_fraction=item["progress_fraction"],
                )
    return state


def read_expedition_progress(campaign, user_id=None, today=None):
    """Read materialized rollups without taking the recomputation write lock."""
    from .models import ExpeditionContribution

    today = today or timezone.localdate()
    if today > campaign.end_date and campaign.finale_snapshot:
        snapshot = campaign.finale_snapshot
        user_key = str(user_id) if user_id is not None else None
        return {
            "participant_count": snapshot["participant_count"],
            "earned_points": Decimal(snapshot["earned_points"]),
            "target_points": Decimal(snapshot["target_points"]),
            "personal_points": Decimal(
                snapshot.get("personal_points_by_participant", {}).get(user_key, "0")
            ),
            "progress_percent": Decimal(snapshot["progress_percent"]),
            "route_percent": Decimal(snapshot.get("route_percent", snapshot["progress_percent"])),
            "personal_progress_percent": Decimal(
                snapshot.get("personal_progress_by_participant", {}).get(user_key, "0")
            ),
        }

    competition = campaign.competition
    participant_ids = (
        set(campaign.participant_ids_snapshot)
        if campaign.locked_at
        else _current_participant_ids(competition)
    )
    if campaign.locked_at and not participant_ids:
        participant_ids = _current_participant_ids(competition)
    participant_count = len(participant_ids)
    periods = list(_score_periods(campaign.start_date, campaign.end_date))
    week_starts = [period[0] for period in periods]
    target_per_person = sum((period[-1] for period in periods), ZERO)
    target_points = target_per_person * participant_count

    earned_points = ZERO
    personal_points = ZERO
    if campaign.locked_at:
        rows = ExpeditionContribution.objects.filter(
            campaign=campaign,
            participant_id__in=participant_ids,
            week_start__in=week_starts,
        )
        earned_points = rows.aggregate(total=Sum("normalized_points"))["total"] or ZERO
        if user_id is not None:
            personal_points = rows.filter(
                participant_id=user_id,
            ).aggregate(total=Sum("normalized_points"))["total"] or ZERO

    return {
        "participant_count": participant_count,
        "earned_points": earned_points,
        "target_points": target_points,
        "personal_points": personal_points,
        "progress_percent": objective_progress_percent(
            campaign, _progress_percent(earned_points, target_points), periods, participant_count, today,
        ),
        "route_percent": _progress_percent(earned_points, target_points),
        "personal_progress_percent": _progress_percent(personal_points, target_per_person),
    }


def expedition_crew_summary(campaign, progress, today=None, user_id=None, milestones=None):
    """Explain the shared route: who is pulling, this week's ceiling, next landmark.

    Built from the materialized ``ExpeditionContribution`` rows, so it never
    rescans Points. Contributors are listed in a neutral (alphabetical) order
    with their share of the pooled points - no ranking and no last place, in
    line with the anti-shaming rule. Empty when the campaign has not launched.
    ``pace_percent`` is where a crew that hits every weekly ceiling would stand
    today - the "today" flag on the map.
    ``milestones`` lets the API hand in the sequence-ordered rows it already
    loaded instead of querying them again.
    """
    from .models import ExpeditionContribution
    from custom_user.models import CustomUser
    from custom_user.serializers import user_picture_url

    today = today or timezone.localdate()
    periods = list(_score_periods(campaign.start_date, campaign.end_date))
    target_per_person = sum((period[-1] for period in periods), ZERO)
    earned_points = Decimal(progress["earned_points"])
    participant_count = int(progress["participant_count"])
    target_points = Decimal(progress["target_points"])

    current_week_start = None
    current_cap = ZERO
    expected_per_person = ZERO
    for week_start, period_start, period_end, _start_dt, _end_dt, cap in periods:
        cap = _effective_cap(campaign, week_start, cap)
        if period_end <= today:
            expected_per_person += cap
        elif period_start <= today < period_end:
            current_week_start = week_start
            current_cap = cap
            elapsed_days = Decimal((today - period_start).days + 1)
            covered_days = Decimal((period_end - period_start).days)
            expected_per_person += (cap * elapsed_days / covered_days).quantize(
                Decimal("0.01"), rounding=ROUND_HALF_UP,
            )
    pace_percent = _progress_percent(expected_per_person * participant_count, target_points)
    storm_percent = None
    if campaign.objective == OBJECTIVE_RESCUE:
        storm_percent = max(Decimal("0.0"), pace_percent - STORM_GRACE_PERCENT)

    contributors = []
    week_earned = ZERO
    if campaign.locked_at:
        participant_ids = set(campaign.participant_ids_snapshot) or _current_participant_ids(campaign.competition)
        rows = ExpeditionContribution.objects.filter(
            campaign=campaign,
            participant_id__in=participant_ids,
            week_start__in=[period[0] for period in periods],
        )
        totals = {
            row["participant_id"]: Decimal(str(row["total"] or 0))
            for row in rows.values("participant_id").annotate(total=Sum("normalized_points"))
        }
        week_totals = {}
        if current_week_start is not None:
            week_totals = {
                row["participant_id"]: Decimal(str(row["total"] or 0))
                for row in rows.filter(week_start=current_week_start)
                .values("participant_id").annotate(total=Sum("normalized_points"))
            }
            week_earned = sum(week_totals.values(), ZERO)
        users = CustomUser.objects.filter(pk__in=participant_ids).only(
            "pk", "first_name", "last_name", "username", "profile_picture",
        )
        for user in sorted(users, key=lambda item: ((item.first_name or "").lower(), item.pk)):
            points = totals.get(user.pk, ZERO)
            week_points = week_totals.get(user.pk, ZERO)
            contributors.append({
                "id": user.pk,
                "name": user.first_name or user.username or "Teammate",
                "is_you": user.pk == user_id,
                "profile_picture": user_picture_url(user),
                "points": float(points),
                "share_percent": float(_progress_percent(points, earned_points)) if earned_points > ZERO else 0.0,
                "personal_progress_percent": float(_progress_percent(points, target_per_person)),
                "week_points": float(week_points),
                "week_energy_percent": float(_progress_percent(week_points, current_cap)) if current_cap > ZERO else 0.0,
            })

    this_week = None
    if current_week_start is not None:
        for week_start, period_start, period_end, _start_dt, _end_dt, cap in periods:
            if week_start == current_week_start:
                this_week = {
                    "start_date": period_start.isoformat(),
                    "end_date": (period_end - timedelta(days=1)).isoformat(),
                    "earned_points": float(week_earned),
                    "possible_points": float(current_cap * participant_count),
                    "cap_per_person": float(current_cap),
                }

    camp = None
    if campaign.objective == OBJECTIVE_BASECAMP and campaign.locked_at:
        status = basecamp_status(
            campaign, periods, participant_count, today,
            _weekly_crew_totals(campaign, [period[0] for period in periods]),
        )
        camp = {key: value for key, value in status.items() if key != "progress_percent"}

    landmark_percent = Decimal(str(progress.get("progress_percent", 0)))
    next_milestone = None
    if milestones is None:
        milestones = list(campaign.milestones.order_by("sequence"))
    for milestone in milestones:
        if milestone.completed_at:
            continue
        needed = (milestone.progress_fraction * target_points).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        next_milestone = {
            "milestone_id": milestone.milestone_id,
            "progress_percent": float(milestone.progress_fraction * Decimal("100")),
            "opens_on": milestone.opens_on.isoformat(),
            "target_on": milestone.target_on.isoformat(),
            "points_to_go": float(max(needed - earned_points, ZERO)),
            "percent_to_go": float(max(milestone.progress_fraction * Decimal("100") - landmark_percent, ZERO)),
            "time_gated": milestone.milestone_id == "finale" or today < milestone.opens_on,
        }
        break

    twist = active_twist(campaign, periods, today) if campaign.locked_at else None
    twists = None
    if campaign.locked_at:
        from .expedition_variants import twist as twist_info
        shortcut = (campaign.twist_state or {}).get("shortcut") or {}
        votes = {str(k): v for k, v in (shortcut.get("votes") or {}).items()}
        current = None
        if twist:
            info = twist_info(twist["kind"]) or {}
            current = {
                "kind": twist["kind"],
                "title": info.get("title"),
                "coach_line": info.get("coach_line"),
                "help": info.get("help"),
                "week_start": twist["week_start"].isoformat(),
                "week_end": twist["week_end"].isoformat(),
            }
        twists = {
            "active": current,
            "plan": [
                {"week_start": item["week_start"], "kind": item["kind"], "title": (twist_info(item["kind"]) or {}).get("title")}
                for item in (campaign.twist_plan or [])
            ],
            "shortcut": {
                "open": bool(twist and twist["kind"] == TWIST_SHORTCUT and not shortcut.get("result")),
                "ridge_votes": sum(1 for v in votes.values() if v == "ridge"),
                "valley_votes": sum(1 for v in votes.values() if v == "valley"),
                "your_vote": votes.get(str(user_id)) if user_id is not None else None,
                "result": shortcut.get("result"),
                "milestone_id": shortcut.get("milestone_id"),
            } if any(item.get("kind") == TWIST_SHORTCUT for item in (campaign.twist_plan or [])) else None,
        }

    return {
        "weekly_cap_per_person": float(current_cap) if current_cap > ZERO else float(WEEKLY_PERSONAL_CAP),
        "target_per_person": float(target_per_person),
        "pace_percent": float(pace_percent),
        "storm_percent": float(storm_percent) if storm_percent is not None else None,
        "camp": camp,
        "twists": twists,
        "contributors": contributors,
        "this_week": this_week,
        "next_milestone": next_milestone,
    }


@transaction.atomic
def recompute_expedition_progress(campaign, user_id=None, today=None, now=None):
    """Recompute fair-share weekly rollups and durable milestone snapshots.

    Each participant can contribute at most 100 normalized points per full
    ISO week, prorated for partial challenge weeks. The route target is one
    such share per participant present at launch per challenge week. The
    unique campaign/participant/week key makes retries and rescoring updates
    idempotent rather than additive.
    """
    from .models import ExpeditionContribution, Points

    today = today or timezone.localdate()
    now = now or timezone.now()
    campaign = synchronize_expedition(campaign, today=today, now=now)
    if today > campaign.end_date and campaign.finale_snapshot:
        snapshot = campaign.finale_snapshot
        user_key = str(user_id) if user_id is not None else None
        personal_points = Decimal(
            snapshot.get("personal_points_by_participant", {}).get(user_key, "0")
        )
        personal_progress_percent = Decimal(
            snapshot.get("personal_progress_by_participant", {}).get(user_key, "0")
        )
        return {
            "participant_count": snapshot["participant_count"],
            "earned_points": Decimal(snapshot["earned_points"]),
            "target_points": Decimal(snapshot["target_points"]),
            "personal_points": personal_points,
            "progress_percent": Decimal(snapshot["progress_percent"]),
            "route_percent": Decimal(snapshot.get("route_percent", snapshot["progress_percent"])),
            "personal_progress_percent": personal_progress_percent,
        }

    competition = campaign.competition
    if campaign.locked_at:
        denominator_ids = set(campaign.participant_ids_snapshot)
        if not denominator_ids:
            denominator_ids = _current_participant_ids(competition)
        participant_ids = denominator_ids
    else:
        denominator_ids = _current_participant_ids(competition)
        participant_ids = denominator_ids

    participant_count = len(denominator_ids)
    if campaign.locked_at:
        RecalcRequest = apps.get_model("custom_user", "RecalcRequest")
        pending_cap_recalculation = RecalcRequest.objects.filter(
            done=False,
            goal__competition_id=competition.pk,
            user_id__in=participant_ids,
        ).exists()
        if pending_cap_recalculation:
            # Never freeze progress or a finale while capped points are stale.
            # The finale date itself is independent of scores, so its milestone
            # may still complete on schedule; the score snapshot waits for the
            # recalc task to clear its request rows.
            if today >= campaign.end_date:
                finale = campaign.milestones.select_for_update().filter(
                    milestone_id="finale",
                ).first()
                if finale and not finale.completed_at and today >= finale.opens_on:
                    finale.completed_at = now
                    finale.coach_snapshot = current_expedition_coach(competition)
                    finale.save(update_fields=["completed_at", "coach_snapshot"])
            return read_expedition_progress(campaign, user_id=user_id, today=today)

    periods = list(_score_periods(campaign.start_date, campaign.end_date))
    target_per_person = sum((period[-1] for period in periods), ZERO)
    target_points = target_per_person * participant_count
    week_starts = []

    if campaign.locked_at:
        # One read for the whole campaign, then a single upsert of the rows
        # that actually changed - the per-participant-per-week
        # update_or_create ran hundreds of queries from a plain GET.
        existing = {
            (row.participant_id, row.week_start): row.normalized_points
            for row in campaign.contributions.all()
        }
        upserts = []
        for week_start, period_start, period_end, start_dt, end_dt, cap in periods:
            week_starts.append(week_start)
            cap = _effective_cap(campaign, week_start, cap)
            rope_week = twist_for_week(campaign.twist_plan, week_start) == TWIST_ROPE
            score_cutoff_date = min(period_end, today + timedelta(days=1))
            if score_cutoff_date <= period_start:
                points_by_participant = {}
            else:
                cutoff_dt = timezone.make_aware(
                    datetime.datetime.combine(score_cutoff_date, datetime.time.min),
                    timezone.get_current_timezone(),
                )
                if rope_week:
                    points_by_participant = _rope_week_points(
                        competition, participant_ids, start_dt, min(end_dt, cutoff_dt),
                    )
                else:
                    totals = (
                        Points.objects.filter(
                            Q(goal__competition_id=competition.pk)
                            | Q(award__competition_id=competition.pk),
                            workout__user_id__in=participant_ids,
                            workout__start_datetime__gte=start_dt,
                            workout__start_datetime__lt=min(end_dt, cutoff_dt),
                        ).distinct()
                        .values("workout__user_id")
                        .annotate(total=Sum("points_capped"))
                    )
                    points_by_participant = {
                        row["workout__user_id"]: Decimal(str(row["total"] or 0))
                        for row in totals
                    }

            for participant_id in sorted(participant_ids):
                points = max(points_by_participant.get(participant_id, ZERO), ZERO)
                normalized = min(points, cap).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
                if existing.get((participant_id, week_start)) == normalized:
                    continue
                upserts.append(ExpeditionContribution(
                    campaign=campaign,
                    participant_id=participant_id,
                    week_start=week_start,
                    normalized_points=normalized,
                ))
        if upserts:
            ExpeditionContribution.objects.bulk_create(
                upserts,
                update_conflicts=True,
                # Mirrors the unique_expedition_participant_week constraint.
                unique_fields=["campaign", "participant", "week_start"],
                update_fields=["normalized_points", "updated_at"],
                batch_size=500,
            )

        campaign.contributions.exclude(week_start__in=week_starts).delete()
        campaign.contributions.exclude(participant_id__in=participant_ids).delete()
        earned_points = campaign.contributions.filter(
            week_start__in=week_starts,
        ).aggregate(total=Sum("normalized_points"))["total"] or ZERO
        personal_points = ZERO
        if user_id is not None:
            personal_points = campaign.contributions.filter(
                participant_id=user_id,
                week_start__in=week_starts,
            ).aggregate(total=Sum("normalized_points"))["total"] or ZERO
    else:
        earned_points = ZERO
        personal_points = ZERO

    route_percent = _progress_percent(earned_points, target_points)
    progress_percent = objective_progress_percent(campaign, route_percent, periods, participant_count, today)
    personal_progress_percent = _progress_percent(personal_points, target_per_person)

    if campaign.locked_at:

        settle_shortcut(campaign, periods, participant_ids, today)
        coach = current_expedition_coach(competition)
        for milestone in campaign.milestones.select_for_update().order_by("sequence"):
            if milestone.completed_at or today < milestone.opens_on:
                continue
            if milestone.milestone_id == "finale":
                # The finale is scheduled for the challenge's actual end date,
                # even when the group finishes short of 100% route progress.
                if today < campaign.end_date:
                    continue
                stamped = progress_percent >= Decimal("100")
            elif progress_percent < milestone.progress_fraction * Decimal("100"):
                continue
            else:
                # Rescue run: the storm reaches a landmark on its date.
                stamped = today <= milestone.target_on
            milestone.completed_at = now
            milestone.coach_snapshot = coach
            milestone.stamped = stamped if campaign.objective == OBJECTIVE_RESCUE else True
            milestone.save(update_fields=["completed_at", "coach_snapshot", "stamped"])

    if today > campaign.end_date and not campaign.finale_snapshot:
        personal_totals = {
            row["participant_id"]: Decimal(str(row["total"] or 0))
            for row in campaign.contributions.filter(week_start__in=week_starts)
            .values("participant_id")
            .annotate(total=Sum("normalized_points"))
        }
        personal_points_by_participant = {
            str(participant_id): str(personal_totals.get(participant_id, ZERO))
            for participant_id in participant_ids
        }
        personal_progress_by_participant = {
            str(participant_id): str(
                _progress_percent(personal_totals.get(participant_id, ZERO), target_per_person)
            )
            for participant_id in participant_ids
        }
        finale_milestone = campaign.milestones.filter(milestone_id="finale").first()
        campaign.finale_snapshot = {
            "final_date": campaign.end_date.isoformat(),
            "participant_count": participant_count,
            "earned_points": str(earned_points),
            "target_points": str(target_points),
            "progress_percent": str(progress_percent),
            "route_percent": str(route_percent),
            "personal_points_by_participant": personal_points_by_participant,
            "personal_progress_by_participant": personal_progress_by_participant,
            "coach": finale_milestone.coach_snapshot if finale_milestone else current_expedition_coach(competition),
        }
        campaign.save(update_fields=["finale_snapshot"])

    return {
        "participant_count": participant_count,
        "earned_points": earned_points,
        "target_points": target_points,
        "personal_points": personal_points,
        "progress_percent": progress_percent,
        "route_percent": route_percent,
        "personal_progress_percent": personal_progress_percent,
    }
