"""
Django settings for workout_challenge project.

Generated by 'django-admin startproject' using Django 4.2.20.
Runtime target is Django 5.2 LTS.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import logging
import datetime, pytz
from pathlib import Path
from urllib.parse import urlparse
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def _get_secret_key():
    """Resolve Django's SECRET_KEY.

    The fallback only fires when SECRET_KEY is unset *and* DEBUG is on -
    so a developer who starts the server without configuring a key can
    still get a working dev setup. In production a missing key is a hard
    error: shipping a known SECRET_KEY would let attackers forge
    sessions, password-reset tokens, and CSRF tokens.
    """
    key = os.environ.get("SECRET_KEY", "").strip()
    if key:
        return key
    if os.environ.get("DEBUG", "false").lower() == "true":
        return 'django-insecure-dev-only-not-for-production-CHANGE-ME-please-50chars'
    raise RuntimeError(
        "SECRET_KEY environment variable is required in production. "
        "Generate one with `python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\"` "
        "and set it via your secrets manager or docker-compose environment."
    )


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _get_secret_key()

# Optional invite token required for new registrations. If unset,
# registration is open (backwards compatible). Set REGISTRATION_TOKEN
# in your (git-ignored) .env - never commit the real token.
REGISTRATION_TOKEN = os.environ.get("REGISTRATION_TOKEN", "").strip()

# Release identifier for the "What's new" popup. Baked into the image at
# build time (CI passes the git tag as a build-arg); "dev" disables the
# popup so local development never nags.
APP_VERSION = os.environ.get("APP_VERSION", "dev").strip()

# Optional explicit key for encrypting stored Garmin OAuth tokens at rest
# (Fernet). Falls back to being derived from SECRET_KEY when unset - set
# this if you rotate SECRET_KEY and want existing Garmin linkages to
# survive the rotation.
GARMIN_TOKEN_KEY = os.environ.get("GARMIN_TOKEN_KEY", "").strip() or None

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false").lower() == "true"
logging.getLogger(__name__).info('Debug mode is %s', 'on' if DEBUG else 'off')

MAIN_HOST = os.environ.get("MAIN_HOST", "http://localhost")
HOSTS = [h.strip() for h in os.environ.get("HOSTS", "http://localhost,http://127.0.0.1").split(",") if h.strip()]


def origin_hostnames(origins):
    """Django ALLOWED_HOSTS entries: hostname only, never host:port."""
    names = []
    for url in origins:
        host = urlparse(url).hostname
        if host:
            names.append(host)
    return names


# CORS / hosts hardening.
# CORS_ALLOW_ALL_ORIGINS *  CORS_ALLOW_CREDENTIALS is forbidden by the
# spec (the browser will refuse the response) and - more importantly -
# means any origin can issue credentialed cross-site requests if a
# browser ever accepts it. Never combine them in production. We default
# to a strict, allow-listed CORS configuration regardless of DEBUG.
CSRF_TRUSTED_ORIGINS = HOSTS
# Django matches ALLOWED_HOSTS against the hostname only (port stripped).
# urlparse().netloc includes ":3000", which never matches Host: localhost
# and is not how Django documents the setting.
ALLOWED_HOSTS = origin_hostnames(HOSTS)
CORS_ALLOWED_ORIGINS = HOSTS
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'celery',
    'django_celery_beat',
    'competition',
    'workouts',
    'custom_user',
    'drill_instructor',
    'site_settings',
    'push_notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'workout_challenge.middleware.BlockPublicMediaMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'workout_challenge.middleware.ApiNoStoreMiddleware',
]

AUTH_USER_MODEL = "custom_user.CustomUser"
ROOT_URLCONF = 'workout_challenge.urls'


# Migration modules for these apps live in src-backend/db_migrations/ -
# deliberately OUTSIDE src-backend/data/, which is a runtime volume in
# the Docker deployment. A named volume keeps its first-seeded content
# forever and would shadow any migrations baked into a newer image, so
# `migrate` at container start could never see them (and the new model
# code would crash against the old schema - e.g. login 500s).
MIGRATION_MODULES = {
    "competition": "db_migrations.competition",
    "workouts": "db_migrations.workouts",
    "custom_user": "db_migrations.custom_user",
    "drill_instructor": "drill_instructor.migrations",
    "site_settings": "site_settings.migrations",
    "push_notifications": "push_notifications.migrations",
    # "django_celery_beat": "db_migrations.django_celery_beat",
    # "django_celery_beat_periodictask": "db_migrations.django_celery_beat_periodictask",
    # "sessions": "db_migrations.sessions",
    # "auth": "db_migrations.auth",
    # "authtoken": "db_migrations.authtoken",
    # "admin": "db_migrations.admin",
    # "contenttypes": "db_migrations.contenttypes",
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'workout_challenge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / 'db.sqlite3',
        "OPTIONS": {
            "timeout": 20,  # seconds
        },
    }
    if os.environ.get("POSTGRES_HOST", None) is None
    else {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "postgres"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": "",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Baseline request throttling. Scoped, stricter buckets ('auth',
    # 'join') are applied to the brute-force-sensitive endpoints
    # (token obtain/refresh, password reset, competition joins).
    'DEFAULT_THROTTLE_CLASSES': [
        'custom_user.throttles.ClientIPAnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '2000/hour',
        'auth': '30/hour',
        # Token REFRESH gets its own, roomier bucket: the tight 'auth'
        # rate exists to stop password guessing on token/, but a refresh
        # token is a 256-bit random value (not brute-forceable), and the
        # app legitimately needs one refresh per access-token expiry
        # (~4/hour per foreground device at 15 min) - plus mobile users
        # share the per-IP budget via carrier-grade NAT. 30/hour here
        # logged users out whenever the app was used regularly.
        'auth_refresh': '300/hour',
        'join': '60/hour',
    },
}

SIMPLE_JWT = {
    # 15 min (was 5): the SPA polls several endpoints plus per-avatar
    # picture fetches. A 5-minute JWT expired in the middle of a session
    # and every poller + every <img> hit the API with a dead token at
    # once - a burst of 401s that CrowdSec http-auth-bf / http-generic-bf
    # treats as credential stuffing. The frontend now also refreshes
    # 60s before expiry; this is the server-side half.
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=15),
    # Effective "stay logged in" duration. With rotation the refresh token
    # is re-issued on every app use, so users only see the login screen
    # after this much *inactivity* - default 31 days = login at most once
    # a month. Override via JWT_REFRESH_DAYS.
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS", "31"))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

PASSWORD_RESET_TIMEOUT = 600  # seconds = 10 minutes

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = CELERY_TIMEZONE = os.environ.get("TIME_ZONE", "Europe/London")
TIME_ZONE_OBJ = pytz.timezone(TIME_ZONE)

USE_I18N = True

USE_TZ = True

# Django 5+: URLField otherwise assumes http:// in forms. Our hosts are HTTPS
# in production; this matches CSRF_TRUSTED_ORIGINS which already carry a scheme.
FORMS_URLFIELD_ASSUME_HTTPS = True


# Security headers - Django emits these on every response. nginx also
# sets some headers (see nginx.conf) so we set both for defense in
# depth: nginx is in front of the API for the public compose setup but
# gunicorn is also exposed on :8000 for debugging.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

CACHES = {
    # Redis is always running in this stack (supervisord starts it as
    # the first process). We use it for the cache regardless of DEBUG
    # so that throttles / locks work across all gunicorn workers -
    # LocMemCache is per-process so multi-worker dev runs would have
    # N times the intended throttle threshold.
    'default': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True
            },
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        }
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'apistatic/'
STATIC_ROOT = BASE_DIR / 'static'

# User-uploaded media (profile / photo / Echo pictures). NEVER served
# at this URL: nginx 404s /media/, Django middleware 404s it too, and
# serializers only emit authenticated /api/.../picture/ paths. Files
# live in the data volume and are delivered via X-Accel-Redirect to
# the internal /protected-media/ location after a JWT check.
MEDIA_URL = '/media/'
MEDIA_ROOT = DATA_DIR / 'media'
# nginx (user `nginx`) serves these via X-Accel-Redirect. Default umask
# is usually fine; 0600 thumbs (mkstemp) are not - see images._thumb_rel.
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Strava API
STRAVA_CLIENT_ID = int(os.environ.get("STRAVA_CLIENT_ID", 1234321))
STRAVA_CLIENT_SECRET = os.environ.get("STRAVA_CLIENT_SECRET", "ReplaceWithClientSecret")
STRAVA_LIMIT_15MIN = int(os.environ.get("STRAVA_LIMIT_15MIN", 100))
STRAVA_LIMIT_DAY = int(os.environ.get("STRAVA_LIMIT_DAY", 1000))

# Health (Open Wearables): Apple Health / Health Connect connector.
# BASE_URL + developer credentials are required to enable it (Site
# Settings can override at runtime). PUBLIC_URL is the phone-facing
# address shown in connection codes (falls back to BASE_URL when unset).
HEALTH_BASE_URL = os.environ.get("HEALTH_BASE_URL", "")
HEALTH_PUBLIC_URL = os.environ.get("HEALTH_PUBLIC_URL", "")
HEALTH_DEVELOPER_EMAIL = os.environ.get("HEALTH_DEVELOPER_EMAIL", "")
HEALTH_DEVELOPER_PASSWORD = os.environ.get("HEALTH_DEVELOPER_PASSWORD", "")


# Sentry
if (sentry_sdk_url := os.environ.get("SENTRY_DSN", None)) is not None:
    sentry_sdk.init(
        dsn=sentry_sdk_url,
        environment="backend",
        send_default_pii=False,
        enable_tracing=True,
        traces_sample_rate=0.25,
        profiles_sample_rate=1.0,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(monitor_beat_tasks=True),
        ],
    )


# Emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", None)
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 25))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", None)
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", None)
EMAIL_USE_TLS = None if (use_tls := os.environ.get("EMAIL_USE_TLS", None)) is None else (str(use_tls).lower() in ["true", "1"])
EMAIL_USE_SSL = None if (use_ssl := os.environ.get("EMAIL_USE_SSL", None)) is None else (str(use_ssl).lower() in ["true", "1"])
EMAIL_FROM = DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_FROM", None)
EMAIL_REPLY_TO = None if (reply_email := os.environ.get("EMAIL_REPLY_TO", None)) is None else reply_email.split(",")

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        # This is where Django logs DisallowedHost errors
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# OpenAI for AI quotes
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", None)
# Provider preset: "custom" (default OpenAI-compatible), "MiniMax",
# "openai". Used as a fallback when the Site Settings DB row hasn't
# picked one. Resolved base_url + model are derived from this preset
# unless the DB row overrides them.
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", None)
# Any OpenAI-compatible provider can be used by setting LLM_BASE_URL
# (e.g. https://openrouter.ai/api/v1, https://api.groq.com/openai/v1,
# http://localhost:11434/v1 for Ollama). Leave unset to use the
# provider preset's default endpoint (or OpenAI's endpoint for "custom").
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", None)
# Default model for the Drill Instructor (short, persona-voiced comments).
LLM_MODEL = os.environ.get("LLM_MODEL", "gpt-4o-mini")
# Model used for the weekly email AI fact. Slightly higher quality is
# fine here because it runs once per user per week.
LLM_EMAIL_MODEL = os.environ.get("LLM_EMAIL_MODEL", "gpt-4o")

# Coach feed photo posts: per-user daily cap. Every photo queues an LLM
# reaction (and, with an image-capable provider, an image-edit roast) -
# both cost money per call, so keep this tight.
DRILL_MAX_PHOTOS_PER_DAY = int(os.environ.get("DRILL_MAX_PHOTOS_PER_DAY", 2))

# Optional: a SEPARATE OpenAI-compatible provider for image editing (the
# coach's roasted-photo remix). Chat models that can READ images often
# can't CREATE them (e.g. MiniMax M3) - with these set, the roast edit
# call goes here while chat/vision stay on the main provider above.
# Leave unset to probe the main endpoint for image editing as before.
LLM_IMAGE_BASE_URL = os.environ.get("LLM_IMAGE_BASE_URL", "")
LLM_IMAGE_MODEL = os.environ.get("LLM_IMAGE_MODEL", "")
LLM_IMAGE_API_KEY = os.environ.get("LLM_IMAGE_API_KEY", "")  # falls back to OPENAI_API_KEY
