# Generated by Django 5.2.16 on 2026-08-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_customuser_strava_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_source',
            field=models.CharField(blank=True, choices=[('strava', 'Strava'), ('garmin', 'Garmin')], default=None, max_length=10, null=True),
        ),
    ]
