# Generated by Django 5.2.17 on 2026-09-20 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0011_hash_outstanding_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='goal_active_days',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal_distance',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal_workout_minutes',
            field=models.IntegerField(blank=True, default=150, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
