# Generated by Django 4.2.30 on 2026-07-25 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # NB: NOT initial=True - this migration depends on 0001_initial and
    # would normally follow it. The two existing migrations were both
    # marked initial=True in the original generated source which makes
    # Django treat the second one as if the app had no ancestors and
    # blows up the migration graph. Leaving initial=True on this one
    # worked while running `migrate` against an already-populated DB
    # (Django only loads this migration after a fresh DB read), but
    # it breaks as soon as a new migration follows.

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
        migrations.AddField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='activitygoal',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddConstraint(
            model_name='points',
            constraint=models.UniqueConstraint(fields=('goal', 'award', 'workout'), name='unique_goal_award_workout'),
        ),
    ]
