# Generated by Django 5.2.17 on 2026-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_points_partial_uniques'),
        ('workouts', '0005_alter_workout_sport_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='points',
            name='unique_award_workout',
        ),
        migrations.AlterField(
            model_name='award',
            name='sport',
            field=models.CharField(choices=[('GROUP_ANY', 'Group: All Sports'), ('GROUP_RUNNING', 'Group: Running (Run / Trail / Treadmill)'), ('GROUP_BIKING', 'Group: Biking/Cycling (Except E-Bike)'), ('GROUP_WALKING', 'Group: Walking (Walk / Wheelchair / Elliptical / Stepper)'), ('GROUP_RACKET', 'Group: Racket Sports (Tennis / Squash / Badminton / Pickleball / Padel / Racquetball / Table Tennis)'), ('GROUP_SOCIAL', 'Group: Ball Sports (Soccer / Basketball / Volleyball / Cricket / Golf)'), ('GROUP_COMBAT', 'Group: Combat Sports (Muay Thai / Boxing / Kickboxing / Martial Arts)'), ('GROUP_CLASSES_CARDIO', 'Group: Cardio Gym Classes (Crossfit / HIIT / Dance)'), ('GROUP_CLASSES_MINDFUL', 'Group: Mindfulness Classes (Yoga / Pilates)'), ('GROUP_WATER_ACTIVE', 'Group: Active Water Sports (Swim / Canoe / Kayak / Kitesurf / Rowing / Surfing / Windsurf)'), ('Steps', 'Total Daily Steps'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Boxing', 'Boxing'), ('Ride', 'Biking/Cycling'), ('EBikeRide', 'Biking/Cycling (E-Bike)'), ('GravelRide', 'Biking/Cycling (Gravel)'), ('Handcycle', 'Biking/Cycling (Handcycle)'), ('Velomobile', 'Biking/Cycling (Velomobile)'), ('VirtualRide', 'Biking/Cycling (Virtual)'), ('Canoeing', 'Canoe'), ('Cricket', 'Cricket'), ('Crossfit', 'Crossfit'), ('Dance', 'Dance'), ('Elliptical', 'Elliptical'), ('Golf', 'Golf'), ('HighIntensityIntervalTraining', 'High Intensity Interval Training (HIIT)'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayak'), ('Kickboxing', 'Kickboxing'), ('Kitesurf', 'Kitesurf'), ('MartialArts', 'Martial Arts'), ('MountainBikeRide', 'Mountain-Biking/Cycling'), ('EMountainBikeRide', 'Mountain-Biking/Cycling (E-Bike)'), ('MuayThai', 'Muay Thai'), ('Padel', 'Padel'), ('Pickleball', 'Pickleball'), ('Pilates', 'Pilates'), ('PhysicalTherapy', 'Physical Therapy'), ('Racquetball', 'Racquetball'), ('RockClimbing', 'Rock Climbing'), ('Rowing', 'Rowing (Outdoor)'), ('VirtualRow', 'Rowing (Virtual)'), ('Run', 'Run'), ('TrailRun', 'Run (Trail)'), ('VirtualRun', 'Run (Treadmill / Virtual)'), ('Volleyball', 'Volleyball'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('AlpineSki', 'Ski (Alpine)'), ('BackcountrySki', 'Ski (Backcountry)'), ('NordicSki', 'Ski (Nordic)'), ('RollerSki', 'Ski (Roller/Inliner)'), ('Snowboard', 'Snowboard'), ('Soccer', 'Soccer / Football'), ('Squash', 'Squash'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand-up Paddling'), ('Surfing', 'Surf'), ('Swim', 'Swim'), ('TableTennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('Walk', 'Walk'), ('Snowshoe', 'Walk (Snowshoe)'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Yoga', 'Yoga'), ('Workout', 'Other Workout')], default='GROUP_ANY', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='points',
            constraint=models.UniqueConstraint(condition=models.Q(('award__isnull', False), ('goal__isnull', True)), fields=('award', 'workout'), name='unique_award_workout'),
        ),
    ]
