# Generated by Django 5.2.17 on 2026-09-20 12:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_remove_points_unique_award_workout_alter_award_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygoal',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='activitygoal',
            constraint=models.CheckConstraint(condition=models.Q(('goal__gt', 0)), name='activitygoal_goal_positive'),
        ),
    ]
