# Generated by Django 5.2.17 on 2026-09-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_award_unique_award_per_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Pilot flag: expose the Expedition to challenge participants.')),
                ('route_template', models.CharField(default='trail-v1', editable=False, max_length=40)),
                ('start_date', models.DateField(editable=False)),
                ('end_date', models.DateField(editable=False)),
                ('locked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expedition', to='competition.competition')),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.SlugField(max_length=40)),
                ('milestone_id', models.SlugField(max_length=40)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('opens_on', models.DateField()),
                ('target_on', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coach_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_asset_key', models.CharField(blank=True, default='', max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='competition.expeditioncampaign')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='expeditioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='expedition_dates_are_ordered'),
        ),
        migrations.AddConstraint(
            model_name='expeditionmilestone',
            constraint=models.UniqueConstraint(fields=('campaign', 'milestone_id'), name='unique_expedition_milestone_key'),
        ),
        migrations.AddConstraint(
            model_name='expeditionmilestone',
            constraint=models.UniqueConstraint(fields=('campaign', 'sequence'), name='unique_expedition_milestone_sequence'),
        ),
    ]
