# Generated by Django 5.2.17 on 2026-09-29 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_expeditioncampaign_expeditionmilestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditioncampaign',
            name='participant_ids_snapshot',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='expeditionmilestone',
            name='progress_fraction',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
        migrations.CreateModel(
            name='ExpeditionContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('normalized_points', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='competition.expeditioncampaign')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start', 'participant_id'],
                'indexes': [models.Index(fields=['campaign', 'week_start'], name='expedition_week_lookup')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'participant', 'week_start'), name='unique_expedition_participant_week')],
            },
        ),
    ]
