# Generated by Django 5.2.17 on 2026-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_expeditioncampaign_participant_ids_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditioncampaign',
            name='finale_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
