# Generated by Django 5.2.17 on 2026-09-30 12:27

from django.db import migrations, models


def _existing_campaigns_are_summits(apps, schema_editor):
    ExpeditionCampaign = apps.get_model("competition", "ExpeditionCampaign")
    ExpeditionCampaign.objects.filter(route_theme="").update(route_theme="summit")


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_expeditioncampaign_finale_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditioncampaign',
            name='objective',
            field=models.CharField(choices=[('expedition', 'Expedition - reach the far end together'), ('rescue', 'Rescue run - stay ahead of the storm'), ('basecamp', 'Base camp - hold the camp week after week'), ('treasure', 'Treasure hunt - hidden landmarks')], default='expedition', max_length=20),
        ),
        migrations.AddField(
            model_name='expeditioncampaign',
            name='route_theme',
            field=models.CharField(blank=True, default='', help_text='Blank = rotate automatically (summit, ocean, desert, space, relay).', max_length=20),
        ),
        migrations.AddField(
            model_name='expeditioncampaign',
            name='twist_plan',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='expeditioncampaign',
            name='twist_state',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='expeditionmilestone',
            name='stamped',
            field=models.BooleanField(default=True),
        ),
        # Campaigns created before themes existed were all the summit trail;
        # keep their postcards and maps unchanged.
        migrations.RunPython(_existing_campaigns_are_summits, migrations.RunPython.noop),
    ]
