# Generated by Django 5.2.17 on 2026-09-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_encrypt_site_settings_secrets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_reply_to',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_use_tls',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='health_base_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='health_developer_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='health_developer_password',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='health_public_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='llm_api_key',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='llm_base_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='llm_email_model',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='llm_provider',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='strava_client_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='strava_client_secret',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='strava_limit_15min',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='strava_limit_day',
        ),
    ]
